name: Java CI

on:
  push:
    branches:
      - main
      - bs/issue-1
  pull_request:
    branches:
      - main
      - bs/issue-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Specify the JDK version you are using

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
